// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using csvToDatabase.Models;

namespace csvToDatabase.Migrations
{
    [DbContext(typeof(PDDbContext))]
    partial class PDDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("csvToDatabase.Models.Runway", b =>
                {
                    b.Property<int>("runway_id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ident")
                        .IsRequired();

                    b.Property<string>("latitude")
                        .IsRequired();

                    b.Property<string>("longitude")
                        .IsRequired();

                    b.Property<string>("name")
                        .IsRequired();

                    b.Property<string>("runway")
                        .IsRequired();

                    b.Property<DateTime>("updatedAt");

                    b.HasKey("runway_id");

                    b.ToTable("Runways");
                });
#pragma warning restore 612, 618
        }
    }
}
